[tool.poetry]
name = "decli-git-demo"
version = "0.1.0"
description = "A git like demo"
authors = ["Santiago Fraire <santiwilly@gmail.com>"]

[tool.poetry.dependencies]
python = "*"
decli = "^0.5.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
flake8 = "^3.5"
mypy = "^0.620.0"
